<h1> Cours 1 : Programmation Python (TP 1 à 3) <span class="tocSkip"></span></h1>

<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Première-Partie-(2H30)" data-toc-modified-id="Première-Partie-(2H30)-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Première Partie (2H30)</a></span><ul class="toc-item"><li><span><a href="#Cours-(1H)" data-toc-modified-id="Cours-(1H)-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Cours (1H)</a></span><ul class="toc-item"><li><span><a href="#Calculs" data-toc-modified-id="Calculs-1.1.1"><span class="toc-item-num">1.1.1&nbsp;&nbsp;</span>Calculs</a></span></li><li><span><a href="#Incrémentation" data-toc-modified-id="Incrémentation-1.1.2"><span class="toc-item-num">1.1.2&nbsp;&nbsp;</span>Incrémentation</a></span></li><li><span><a href="#Boucle" data-toc-modified-id="Boucle-1.1.3"><span class="toc-item-num">1.1.3&nbsp;&nbsp;</span>Boucle</a></span></li><li><span><a href="#Test" data-toc-modified-id="Test-1.1.4"><span class="toc-item-num">1.1.4&nbsp;&nbsp;</span>Test</a></span></li><li><span><a href="#Fonctions" data-toc-modified-id="Fonctions-1.1.5"><span class="toc-item-num">1.1.5&nbsp;&nbsp;</span>Fonctions</a></span></li></ul></li><li><span><a href="#Exercices-(1H30)" data-toc-modified-id="Exercices-(1H30)-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Exercices (1H30)</a></span><ul class="toc-item"><li><span><a href="#Premier-exercice" data-toc-modified-id="Premier-exercice-1.2.1"><span class="toc-item-num">1.2.1&nbsp;&nbsp;</span>Premier exercice</a></span></li><li><span><a href="#Deuxième-exercice" data-toc-modified-id="Deuxième-exercice-1.2.2"><span class="toc-item-num">1.2.2&nbsp;&nbsp;</span>Deuxième exercice</a></span></li><li><span><a href="#Troisième-exercice" data-toc-modified-id="Troisième-exercice-1.2.3"><span class="toc-item-num">1.2.3&nbsp;&nbsp;</span>Troisième exercice</a></span></li><li><span><a href="#Quatrième-exercice" data-toc-modified-id="Quatrième-exercice-1.2.4"><span class="toc-item-num">1.2.4&nbsp;&nbsp;</span>Quatrième exercice</a></span></li></ul></li></ul></li><li><span><a href="#Deuxième-Partie-(4H15)" data-toc-modified-id="Deuxième-Partie-(4H15)-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Deuxième Partie (4H15)</a></span><ul class="toc-item"><li><span><a href="#Cours-(1H)" data-toc-modified-id="Cours-(1H)-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Cours (1H)</a></span><ul class="toc-item"><li><span><a href="#Numpy" data-toc-modified-id="Numpy-2.1.1"><span class="toc-item-num">2.1.1&nbsp;&nbsp;</span>Numpy</a></span><ul class="toc-item"><li><span><a href="#Import" data-toc-modified-id="Import-2.1.1.1"><span class="toc-item-num">2.1.1.1&nbsp;&nbsp;</span>Import</a></span></li><li><span><a href="#Liste,-conversion,-array" data-toc-modified-id="Liste,-conversion,-array-2.1.1.2"><span class="toc-item-num">2.1.1.2&nbsp;&nbsp;</span>Liste, conversion, array</a></span></li><li><span><a href="#Calcul-numérique" data-toc-modified-id="Calcul-numérique-2.1.1.3"><span class="toc-item-num">2.1.1.3&nbsp;&nbsp;</span>Calcul numérique</a></span></li><li><span><a href="#Calcul-matriciel" data-toc-modified-id="Calcul-matriciel-2.1.1.4"><span class="toc-item-num">2.1.1.4&nbsp;&nbsp;</span>Calcul matriciel</a></span></li><li><span><a href="#Indexation" data-toc-modified-id="Indexation-2.1.1.5"><span class="toc-item-num">2.1.1.5&nbsp;&nbsp;</span>Indexation</a></span></li><li><span><a href="#Manipulation-de-dimensions" data-toc-modified-id="Manipulation-de-dimensions-2.1.1.6"><span class="toc-item-num">2.1.1.6&nbsp;&nbsp;</span>Manipulation de dimensions</a></span></li></ul></li><li><span><a href="#Pandas,-matplotlib" data-toc-modified-id="Pandas,-matplotlib-2.1.2"><span class="toc-item-num">2.1.2&nbsp;&nbsp;</span>Pandas, matplotlib</a></span></li></ul></li><li><span><a href="#Exercices-(3H15)" data-toc-modified-id="Exercices-(3H15)-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>Exercices (3H15)</a></span><ul class="toc-item"><li><span><a href="#Premier-exercice-(numpy-only)" data-toc-modified-id="Premier-exercice-(numpy-only)-2.2.1"><span class="toc-item-num">2.2.1&nbsp;&nbsp;</span>Premier exercice (numpy only)</a></span></li><li><span><a href="#Deuxième-exercice" data-toc-modified-id="Deuxième-exercice-2.2.2"><span class="toc-item-num">2.2.2&nbsp;&nbsp;</span>Deuxième exercice</a></span></li><li><span><a href="#Troisième-exercice" data-toc-modified-id="Troisième-exercice-2.2.3"><span class="toc-item-num">2.2.3&nbsp;&nbsp;</span>Troisième exercice</a></span></li></ul></li></ul></li></ul></div>

Dans ce premier cours, nous allons nous familiariser avec le language Python et l'environnement Jupyter Notebook ainsi que les principaux packages indispensables au Data Scientist Python. <br>

La plupart des morceaux de programmes sont déjà écrits, il suffit de faire SHIFT+ENTER lorsque la cellule est sélectionnée pour lancer le code. <br>

Lorsque "##Votre Code##" apparait dans une cellule, c'est à vous de jouer et de briller ! Si le code est bon, un message "Bravo" sera affiché en sortie. <br>

À la fin de chaque partie, il y a au moins 2 exercices pour vous entraîner. Un simple et des plus difficiles.


# Première Partie (2H30)

Dans cette première partie, nous introduisons les éléments de programmation simple tel que les calculs, l'incrémentation, les boucles, les tests et les fonctions.

## Cours (1H)

### Calculs

L'opération "=" correspond à affecter un nombre à une variable. 
L'objet "None" est un objet passe-partout qui correspond à un élément vide, dans cet exercice il faut le remplacer par la valeur correspondante.<br>

Calculez mentalement :
\begin{equation*}
w=a\times b+c\times d \\
x=a+c/d \\
y=(a+c)/d \\
z=c\%d+a \\
\end{equation*}

In [1]:
a = 3
b = 5
c = 8
d = 2

##Votre Code##
w = None
x = None
y = None
z = None
###Fin du Code###

if w==a*b+c*d and x==a+c/d and y==(a+c)/d and z==c%d+a:
    print("Bravo !")
else:
    print("Essaye encore")


Essaye encore


### Incrémentation 

L'incrémentation consiste à changer le contenu d'une variable en se basant sur son ancienne valeur. <br>

La commande "print" affiche en sortie le résultat demandé. <br>
Le # permet d'écrire des commentaires dans la cellule.<br>

Essayez de trouver les 3 différentes valeurs prises par x avant de retirer les # pour voir les résultats. 



In [5]:
x = 5
x = x + 1
#print (x)
x += 6
#print (x)
x -= 6
#print (x)

### Boucle

La boucle "for" est très pratique pour les calculs incrémentales, voici un exemple. <br>

Questions:
- Combien de fois la boucle est-elle parcourue ?
- Quels sont les nombres qui doivent apparaître en sortie ?

In [9]:
for i in range(1,5):
    x = x + i 
    #print(x)

### Test

Un test "if" permet de lancer le programme à l'intérieur du "if" lorsque la condition est respectée.

In [11]:
 x = 8
if x > 0:
    print ("Nombre positif")
else:
    print ("Nombre négatif")

Nombre positif


À vous de jouer, tester la parité de y pour que le résultat affiché soit "Nombre impair".

In [32]:
##Votre Code##
y = 7
if ...:
###Fin du Code###    
    print ("Nombre pair")
    print ("Essaye encore")
else:
    print ("Nombre impair")
    print("Bravo !")


Nombre pair
Essaye encore


### Fonctions

L'écriture de fonctions est l'un des principes essentielles de la programmation. Il permet d'éviter les redondances, avoir un programme plus esthétique et bien d'autres aspects positifs.

Questions : 
- Qu'est ce que je veux faire avec cette fonction ci-dessous ?
- Une facon sans boucle de le faire ? Implémentez-là.  

In [184]:
def fonction(x):
    y=0
    for i in range(1,x+1):
        y+=i
    return y

In [224]:
##Votre Code##
def votre_function(x):
    ...
    return
###Fin du Code###

In [189]:
if fonction(100)==votre_function(100):
    print("Bravo !")
else:
    print("Essaye encore, c'est une somme populaire ;)")

Bravo !


Même si une boucle est très pratique, son coût de calcul est assez élevé, s'il y a une façon de la contourner, utilisez-là ! <br>
Regardons le runtime de ces deux fonctions pour un chiffre très grand afin de s'en convaincre.

In [196]:
import time
import numpy as np
start = time.time()
fonction(100000000)
end = time.time()
print("Avec Boucle "+str(np.round(end-start,5))+"s")
start = time.time()
votre_function(100000000)
end = time.time()
print("Sans Boucle "+str(np.round(end-start,5))+"s")

Avec Boucle 6.7182s
Sans Boucle 4e-05s


## Exercices (1H30)

### Premier exercice 

Interpréter les codes suivants, expliquer en commentaire pourquoi il y a une erreur, et corrigez-les.

In [130]:
#J'aimerais voir 9
a = 5
a + 4
print (a)
if a==9:
    print("Bravo !")
else:
    print("Essaye encore")

5
Corrigez moi svp


In [131]:
#Je veux la somme de 1 à 9
a = 0
for i in range (1, 10) 
    a += i
print (a) 
if a==45:
    print("Bravo !")
else:
    print("Essaye encore")

SyntaxError: invalid syntax (<ipython-input-131-a1c6c1efbd08>, line 3)

In [132]:
#Je veux la somme de 1 à 4
a = 0
for i in range (0, 4)
        a = a + i
    print (a)
if a==10:
    print("Bravo !")
else:
    print("Essaye encore")     

SyntaxError: invalid syntax (<ipython-input-132-ddfaefc1e96c>, line 3)

In [133]:
# Je veux écrire l'adresse de l'université 
a = 45
s = "Rue des Saints-Pères"
print (a + s)
if (a+s=="45 Rue des Saints-Pères"):
    print("Bravo !")
else:
    print("Essaye encore")

TypeError: unsupported operand type(s) for +: 'int' and 'str'

### Deuxième exercice

Ecrivez-moi deux différentes fonctions pour calculer une factorielle  (une itérative et une récursive).

In [162]:
##Votre Code##
def factorielle_iter(x):
    ...
    return
###Fin du Code###
if factorielle_iter(6)==720:
    print("Bravo pour la méthode itérative !")
else:
    print("Essaye encore")

In [223]:
##Votre Code##
def factorielle_recur(x):
    ...
    return
###Fin du Code###

if factorielle_iter(6)==720:
    print("Bravo pour la méthode itérative !")
else:
    print("Essaye encore")

Essaye encore


### Troisième exercice

Calculez la somme des factorielles de 1 à x.

In [201]:
##Votre Code##
def sum_facto(x):
    ...
    return
###Fin du Code###

if sum_facto(20)==2561327494111820313:
    print ("Bravo !")
else:
    print ("Essaye encore ")

### Quatrième exercice

Ecrivez une fonction qui compte le nombre de voyelles.

In [227]:
##Votre Code##
def compte_voyelles(mot):
    ...
    return 
###Fin du Code###

if compte_voyelles("voiture")==4 and compte_voyelles("maison")==3:
    print("Bravo, tu as fini la première partie du cours !")
else: 
    print("Encore un peu pour finir la première partie du cours !")


Encore un peu pour finir la première partie du cours !


# Deuxième Partie (4H15)

Dans cette seconde partie, nous explorerons les packages numpy, pandas et matplotlib essentielles à posséder dans son arsenal.

## Cours (1H)

### Numpy

La plupart des calculs en apprentissage statistique sont des opérations matricielles. Le package numpy contient tous les outils pour faire ses opérations de la façon la plus optimale. <br>

#### Import 

Le package numpy est présent dans n'importe quelle installation d'un IDE Python, notamment Jupyter Notebook. Il suffit donc de l'importer :

In [230]:
import numpy

Généralement, on donne un alias à un package car il contient une multitude de fonctions et comme le programmeur est paresseux, il préfère écrire moins. L'alias admis de tous pour numpy est np.

In [232]:
import numpy as np

#### Liste, conversion, array

Pour stocker plusieurs éléments dans un seul objet, on utilise le concept de liste. Comme son nom l'indique, ce n'est simplement qu'une liste de termes. (Cela peut être des nombres mais aussi des caractères, ou un mélange des deux). <br>


In [275]:
l1 = [1,3,4,6]
l2 = ["a",2,"b",4]

Que se passe-t-il si l'on "somme" deux listes ?

In [276]:
l1+l2

[1, 3, 4, 6, 'a', 2, 'b', 4]

Elle se concatène pour n'en former qu'une seule. <br>

On ne peut pas faire d'opération directement avec les listes, il faut passer par l'objet array de numpy. Retenez bien les arguments que l'on peut obtenir d'un array, notamment dtype et shape.

In [277]:
a = np.array(l1)
print(a)
print(a.dtype)
print(a.ndim)
print(a.shape)

[1 3 4 6]
int64
1
(4,)


Lorsque vous allez faire des calculs entre array, vérifiez bien que vous traitez des nombres. Contrairement à une liste, un array a un unique type (integer, float, string). Si une liste contient au moins un string, le array converti sera un Unicode String (U1) :

In [278]:
s = np.array(l2)
s.dtype

dtype('<U1')

Si vous avez une liste de string mais qu'ils sont en réalité des entiers, on peut forcer une conversion avec astype :

In [301]:
l3 = ["1","2","3"]
b = np.array(l3)
b.astype(int)

array([1, 2, 3])

#### Calcul numérique

Toutes les opérations de calcul sont possibles entre des arrays de même longueur et dimension, l'addition, la soustraction, la multiplication.

In [358]:
a = np.array([1,10,100])
b = np.array([2,3,10])
print(a+b)
print(a-b)
print(a*b)

[  3  13 110]
[-1  7 90]
[   2   30 1000]


Expliquez ce que fais cette commande :

In [365]:
np.exp(a)+b**2
# Explication

array([6.71828183e+00, 2.20354658e+04, 2.68811714e+43])

#### Calcul matriciel

On a construit des array de dimension 1, aussi appelé 1d-array, maintenant on va construire des objets de forme matricielle : des 2d-array. Il faut partir d'une liste de listes.

In [303]:
l4 = [[1,2,3],[2,3,4],[3,4,5]]
matrix = np.array(l4)
print(matrix.ndim)
print(matrix.shape)

2
(3, 3)


NB : le 2d-array se remplit ligne par ligne, ie [1,2,3] est la première ligne de la matrice.

Comme dans la session d'avant, on se chauffe par des calculs. <br>
Calculez :
\begin{equation*}
a=\begin{pmatrix} 
1 & 2 & 3  \\
2 & 3 & 4 \\
3 & 4 & 5 
\end{pmatrix}
\begin{pmatrix} 
1 & 2 & 3  \\
2 & 3 & 4 \\
3 & 4 & 5 
\end{pmatrix}\\
b=\begin{pmatrix} 
1 & 2 & 3  \\
2 & 3 & 4 \\
3 & 4 & 5 
\end{pmatrix}
+
\begin{pmatrix} 
1 & 2 & 3  \\
2 & 3 & 4 \\
3 & 4 & 5 
\end{pmatrix}\\
c=\begin{pmatrix} 
1 & 2 & 3  \\
2 & 3 & 4 \\
3 & 4 & 5 
\end{pmatrix}
\begin{pmatrix} 
1 & 2 & 3  \\
2 & 3 & 4 \\
3 & 4 & 5 
\end{pmatrix}^T
\end{equation*}

In [320]:
##Votre Code##
a = np.array([[None,None,None]]*3)
b = np.array([[None,None,None]]*3)
c = np.array([[None,None,None]]*3)
###Fin du Code###

if np.array_equal(a,matrix*matrix) and np.array_equal(b,matrix+matrix) and np.array_equal(c,matrix*matrix.T):
    print("Bravo !")
else:
    print("Essaye encore")

Essaye encore


#### Indexation

Contrairement à R, l'indexation des arrays commencent à 0 (tout comme C et Java). <br>
Pour accéder à un élément on utilise les crochets []. Par exemple le nombre à la première ligne et la première colonne d'une matrice m est obtenue par m[0,0]. <br>
Pour accéder à tous les éléments d'une ligne ou d'une colonne on peut utiliser ":". <br>

En utilisant la matrice \begin{equation*}m=
\begin{pmatrix} 
1 & 2 & 3  \\
4 & 5 & 6 \\
7 & 8 & 9 
\end{pmatrix}
\end{equation*}
donner moi les éléments suivants (en utilisant l'indexation) :
- m1 = 2 
- m2 = [4,5,6]
- m3 = [3,6,9]
- m4 = [5,8]




In [332]:
m=np.array([[1,2,3],[4,5,6],[7,8,9]])
##Votre Code##
m1 = None
m2 = np.array([None,None,None])
m3 = np.array([None,None,None])
m4 = np.array([None,None])
###Fin du Code###

if np.array_equal(m1,2) and np.array_equal(m2,[4,5,6]) and np.array_equal(m3,[3,6,9]) and np.array_equal(m4,[5,8]):
    print("Bravo !")
else:
    print("Essaye encore")

Essaye encore


#### Manipulation de dimensions

La méthode reshape permet de changer la forme de l’array. On précise à reshape la forme souhaitée: par un entier si on veut un 1d-array, ou un couple (n lignes, p colonnes) pour un 2d-array. <br>

Quelques autres méthodes utiles de numpy.
- np.arange(n) : crée un array contenant les chiffres de 0 à n-1. 
- np.zeros(n) : crée un array contenant n zeros.
- np.ones(n) : crée un array contenant n uns.
- np.concatenate((a,b,c)) : concatène les arrays a,b et c. 

À vous de jouer :
- Construisez un array x de 0 à 6.
- Construisez un array y contenant 2 zeros.
- Construisez un array z contenant 3 uns.
- Concatenez x,y,z et stocker le sous la variable g.
- redimensionnez g en un 2d-array avec 4 lignes et 3 colonnes et appelez le h.

In [353]:
##Votre Code## 
...
### Fin du Code###
if np.array_equal(h,np.array([[0,1,2],[3,4,5],[6,0,0],[1,1,1]])):
    print("Bravo !")
else:
    print("Essaye encore")

Bravo !


### Pandas, matplotlib

Le package pandas est très utilisé pour stocker des bases de données et faire des opérations dessus. Il est l'équivalent du dataframe dans R, dans ce cours nous travaillerons très peu avec pandas. <br>
Le package matplotlib est le package principal pour faire de la visualisation en Python.<br>

Je vous laisse le soin de les explorer en profondeur et de me faire des jolies graphiques pour le projet final, un aperçu des possibilités de matplotlib [içi](https://matplotlib.org/gallery/index.html).<br>

Le dernier exercice vous initie à utiliser les fonctions basiques pour créer un graphique. 


## Exercices (3H15)

### Premier exercice (numpy only)

Questions : 
- Téléchargez les données de "data/data_C1.txt" en les stockant dans un array.
- Donnez le shape de cet array.
- À quoi peuvent correspondre les 2 lignes de cet array ? Redimensionnez-le sous le format standard (observations,variables). 
- Calculez les estimateurs des Moindres Carrés Ordinaires en supposant que la première ligne (Y) est régressée sur la seconde (X).
- Effectuez un test de significativité pour le coefficient de X, donnez la p-value.

Rappel 1 : On minimise la somme des résidus au carré sous les paramètres, pour obtenir les estimateurs des MCO.

Rappel 2 : Test de Student pour la significativité du coefficient de X.

Il s’agit de comparer le coefficient de X donné par les MCO à 0.
Soit X une série de valeurs de taille n, de moyenne m et d’écart-type s. La statistique de test de Student est donné par la formule :

\begin{equation*}
t=\frac{m−0}{s/\sqrt{df}}
\end{equation*}
où df = n-1

t suit sous H_0 une loi de Student de degré de liberté df.

In [485]:
##Votre Code##
...
intercept = None
coef = None
p_value = None
###Fin du Code###


In [486]:
if np.round(coef,2)==0.54 and np.round(intercept,2)==134.53 and np.round(2*p_uni,10)==4e-10:
    print("Bravo !")
else:
    print("Essaye encore")

TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'

### Deuxième exercice

Construisez un échiquier de 2 façons différentes : 
- Avec une indexation astucieuse (Essayer "::2" pour sauter un pas).
- Avec la fonction tile.


In [421]:
##Votre Code##
echiquier_1 = ...
###Fin du Code###

if np.array_equal(echiquier_1,np.array(
[[1,0,1,0,1,0,1,0],
 [0,1,0,1,0,1,0,1],
 [1,0,1,0,1,0,1,0],
 [0,1,0,1,0,1,0,1],
 [1,0,1,0,1,0,1,0],
 [0,1,0,1,0,1,0,1],
 [1,0,1,0,1,0,1,0],
 [0,1,0,1,0,1,0,1]])):
    print("Bravo !")
else:
    print("Essaye encore")

Essaye encore


In [422]:
##Votre Code##
echiquier_2 = ...
###Fin du Code###

if np.array_equal(echiquier_2,np.array(
[[1,0,1,0,1,0,1,0],
 [0,1,0,1,0,1,0,1],
 [1,0,1,0,1,0,1,0],
 [0,1,0,1,0,1,0,1],
 [1,0,1,0,1,0,1,0],
 [0,1,0,1,0,1,0,1],
 [1,0,1,0,1,0,1,0],
 [0,1,0,1,0,1,0,1]])):
    print("Bravo !")
else:
    print("Essaye encore")

Essaye encore


### Troisième exercice

Une marche aléatoire Y est un processus stochastique tel que :
\begin{equation*}
Y_0 = 0\\
Y_n =\sum \limits_{i=1}^{n} X_i \text{  , pour tout n>0}
\end{equation*}
où $X_i$ suit une Bernouilli sur le support {-1,1}.<br>

Questions :
- Simulez 10 marches aléatoires de taille n=1000, et de pas +1 ou -1 équiprobables.
- Utilisez matplotlib pour ploter les 10 marches aléatoires.
- Légendez les abscisses, ordonnées.
- Donnez le titre "A Random Walk" au graphique.  
- Donnez la plus haute et la plus petite valeur pour ses 10 marches. 
- Moyenne d'étapes pour dépasser la valeur 20 sur ces marches ?

In [533]:
np.random.seed(26)
##Votre Code##

###Fin du Code###